#:schema https://mise.en.dev/schema/mise.json

[settings]
color = true
pipx.uvx = true
experimental = true
color_theme = "charm"
minimum_release_age_excludes = ["bun", "node", "npm:oxfmt", "npm:oxlint"]

[tools]
bun = "latest"
node = "latest"
tombi = "latest"
usage = "latest"
shfmt = "latest"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
