#:schema https://mise.en.dev/schema/mise.json

[settings]
color = true
pipx.uvx = true
experimental = true
color_theme = "charm"
minimum_release_age_excludes = [
  "hk",
  "uv",
  "pkl",
  "bun",
  "node",
  "npm:oxfmt",
  "npm:oxlint"
]

[env]
HK_MISE = 1
UV_PREVIEW = 1

[tools]
hk = "latest"
uv = "latest"
bun = "latest"
pkl = "latest"
node = "latest"
shfmt = "latest"
tombi = "latest"
usage = "latest"
ghalint = "latest"
gitleaks = "latest"
shellcheck = "latest"
actionlint = "latest"
betterleaks = "latest"

[hooks]
postinstall = "hk install --mise"

[tasks]
description = "run tests"
run = "bun test"

[tasks.check]
description = "format & lint files"
run = "hk fix --all && hk check --all"

[tasks.ci]
description = "run CI tasks"
run = "hk fix --all && hk check --all && bun test"
