name: Checks
description: "Run format, lint, type check, and build checks."

runs:
  using: "composite"
  steps:
    - name: "Setup mise 🐭"
      uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
      with:
        cache: false

    - name: "Install Dependencies"
      shell: bash
      run: |
        mise install
        bun install --frozen-lockfile
      env:
        NO_COLOR: "true"

    - name: "Run CI Tasks"
      shell: bash
      run: mise ci
